Bugfix xml extraction
CybercentreCanada/assemblyline-service-oletools pull request #3
Opened 2021-02-22 18:56 UTC by cccs-jh

Reducing irrelevant xml extractions by whitelisting certain IOCS:
- common excel .bin filenames no longer tagged
- dublincore.org schema urls no longer tagged
- no longer extracting based on iocs found in gcdocs urls
- no longer extracting based on common blacklisted strings

Also fixed a powerpoint parsing error (string bytes problem again)

2021-02-22 19:00 UTC, cccs-kevin commented on oletools_/oletools_.py
> +        if 'gcdocs.gc.ca' in val or val == 'llisapi.dll':
should this be hardcoded into th service? it seems way too specific for the general public to be aware of

2021-02-22 19:12 UTC, cccs-jh commented on oletools_/oletools_.py
> +        if 'gcdocs.gc.ca' in val or val == 'llisapi.dll':
possibly not, I could create a whitelist variable in the config

2021-02-22 19:15 UTC, cccs-kevin commented on oletools_/oletools_.py
> +        if 'gcdocs.gc.ca' in val or val == 'llisapi.dll':
I like that idea :)

2021-02-22 19:15 UTC, cccs-kevin requested changes
see comment re safelist

2021-02-23 13:15 UTC, cccs-kevin approved these changes

2021-02-23 14:13 UTC, cccs-rs approved these changes

2021-02-23 14:50 UTC, merged